"""Classify BlueprintExport JSONs into CANDIDATE / SKIP / EXCLUDE for the
BlueprintToStaticMeshReplacer workflow.

Inputs:
    --export-root  Directory containing BlueprintExport JSONs. Default:
                   <CWD>/Intermediate/UAssetExport/Game

Outputs (stdout):
    candidates.csv content (Status,Name,AssetPath,LevelRefs,NonEditorComps,
    UserVars,HasLogic,Reason).

Classification rules (must all hold for CANDIDATE):
    1. ParentClass = Actor
    2. NonEditorComponentCount in {1, 2}, with structural shape:
         - 1 component  -> must be StaticMeshComponent (SMC=root)
         - 2 components -> RootComponent must be SceneComponent + exactly 1 SMC
    3. UserVariableCount = 0
    4. HasAnyGraphLogic = false
    5. Referencers_OtherCount = 0       (only level references allowed)
    6. Referencers_LevelCount > 0        (must have at least one instance)

Anything failing rule 6 with rules 1-5 satisfied is SKIP (no instances).
Anything failing 1-5 is EXCLUDE.

Usage:
    python Plugins/MapUtils/Script/BlueprintToStaticMeshReplacer/classify.py > Intermediate/BlueprintToStaticMeshReplacer/candidates.csv
    python Plugins/MapUtils/Script/BlueprintToStaticMeshReplacer/classify.py --export-root <path> --pretty
"""

from __future__ import annotations

import argparse
import csv
import json
import sys
from pathlib import Path
from typing import Tuple

# Force LF line endings on stdout, even on Windows, so downstream tools (paste,
# tr, FParse::Value in UE commandlets) don't trip over CRs embedded in fields.
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(newline="\n")


def classify(d: dict) -> Tuple[str, str]:
    """Return (status, reason)."""
    parent = d.get("ParentClass", "")
    if parent != "Actor":
        return "EXCLUDE", f"parent={parent}"

    non_editor = d["NonEditorComponentCount"]
    components = [c for c in d["Components"] if not c.get("IsEditorOnly")]
    classes = [c["Class"] for c in components]

    if non_editor == 1:
        if classes != ["StaticMeshComponent"]:
            return "EXCLUDE", f"single non-editor comp is {classes[0]}, not SMC"
        shape = "SMC=root"
    elif non_editor == 2:
        root_class = d.get("RootComponentClass")
        if root_class not in ("SceneComponent", "DefaultSceneRoot"):
            return "EXCLUDE", f"root is {root_class}, not SceneComponent"
        sm_count = sum(1 for c in classes if c == "StaticMeshComponent")
        if sm_count != 1:
            return "EXCLUDE", f"2 comps but {sm_count} SMCs"
        shape = "RootScene+SMC"
    else:
        return "EXCLUDE", f"non-editor comp count = {non_editor}"

    if d["UserVariableCount"] > 0:
        user_vars = [v["Name"] for v in d["Variables"] if not v.get("IsAutoGenerated")]
        return "EXCLUDE", f"{d['UserVariableCount']} user vars: {user_vars[:3]}"

    if d["HasAnyGraphLogic"]:
        return "EXCLUDE", "has graph logic (wired pins)"

    if d["Referencers_OtherCount"] > 0:
        others = [
            f"{r.get('AssetClass', '?')}:{r['PackageName'].rsplit('/', 1)[-1]}"
            for r in d["Referencers_Other"][:3]
        ]
        return "EXCLUDE", f"{d['Referencers_OtherCount']} non-level refs: {others}"

    if d["Referencers_LevelCount"] == 0:
        return "SKIP", "no level instances"

    return "CANDIDATE", shape


def iter_exports(export_root: Path):
    for jf in sorted(export_root.rglob("BP_*.json")):
        try:
            yield jf, json.load(jf.open(encoding="utf-8"))
        except Exception as e:
            print(f"[classify] skip unreadable {jf}: {e}", file=sys.stderr)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    parser.add_argument(
        "--export-root",
        default=Path.cwd() / "Intermediate" / "UAssetExport" / "Game",
        type=Path,
    )
    parser.add_argument(
        "--pretty",
        action="store_true",
        help="Print human-readable buckets to stderr instead of CSV to stdout.",
    )
    args = parser.parse_args()

    rows = []
    for _, d in iter_exports(args.export_root):
        status, reason = classify(d)
        rows.append(
            {
                "Status": status,
                "Name": d["Blueprint"],
                "AssetPath": d["AssetPath"].split(".")[0],
                "LevelRefs": d["Referencers_LevelCount"],
                "NonEditorComps": d["NonEditorComponentCount"],
                "UserVars": d["UserVariableCount"],
                "HasLogic": d["HasAnyGraphLogic"],
                "Reason": reason,
            }
        )

    if args.pretty:
        buckets = {"CANDIDATE": [], "SKIP": [], "EXCLUDE": []}
        for r in rows:
            buckets[r["Status"]].append(r)
        for status, items in buckets.items():
            print(f"\n=== {status} ({len(items)}) ===", file=sys.stderr)
            for r in items:
                print(
                    f"  {r['Name']:50s}  refs={r['LevelRefs']:>3}  {r['Reason']}",
                    file=sys.stderr,
                )
        print(f"\nTotal: {len(rows)}", file=sys.stderr)
        return 0

    writer = csv.DictWriter(
        sys.stdout,
        fieldnames=[
            "Status",
            "Name",
            "AssetPath",
            "LevelRefs",
            "NonEditorComps",
            "UserVars",
            "HasLogic",
            "Reason",
        ],
        lineterminator="\n",
    )
    writer.writeheader()
    writer.writerows(rows)
    return 0


if __name__ == "__main__":
    sys.exit(main())
